### ISSUE TITLE
Writing to Field from Form

### ISSUE THREAD

**Issue by philbrookweb** [studioespresso/craft3-easyaddressfield#19]
There is documentation provided to read from the form on the front-end. Is there any way to write to the field from a Form on the front-end? For example, a user profile.

I have no luck at the moment.
Thanks.

**Comment by philbrookweb** [comment]
Actually, I believe I figured this out.

The form input name attribute must be in this format:
`name="fields[fieldname][state]"`
Where "fieldname" is the name of your field in the CMS. For example:
`name="fields[mailingAddress][country]"`

Works fine now!

**Comment by janhenckens** [comment]
Hey there
Happy to see you found it! That's indeed how it works :)

Let me know if you have any other questions or issues.
Cheers
Jan
