### ISSUE TITLE
Map Error: Appended characters atend of URL Req.

### ISSUE THREAD

**Issue by philbrookweb** [studioespresso/craft3-easyaddressfield#20]
Using the following call in my template to grab the Address from a user profile:
`{{ craft.address.getStaticMap(user.vintnerPhysicalAddress, 16, '500x350') }}|raw`

However, it's returning a map image with the following error:
`Map error: g.co/staticmaperror`
with the header error:
`x-staticmap-api-warning | Error geocoding: marker 1`

The requested URL is:
`https://maps.googleapis.com/maps/api/staticmap?zoom=16&size=500x350&scale=1&maptype=roadmap&key=My_Key_1234&style=&markers=color:0xE50000|,`
Which, appends the characters 
> `|,`

to the end of the URL request.

Removing these characters fixes the superimposed `g.co/staticmaperror`, but results in a blank map with only the background color visible:

![Screenshot_2019-09-12 staticmap (PNG Image, 500 × 350 pixels)](https://user-images.githubusercontent.com/49168621/64817201-f086dd80-d56e-11e9-8c84-4759c1682abc.png)

I'm unsure why:
- The characters are being appended
- The map is blank

I suspect the blank map may be an API issue. But the additional characters are either a code mistake or the request url is pulling incorrectly on the front-end because of some missing input somewhere.

Either way, any advice is appreciated.

Thanks!

**Comment by philbrookweb** [comment]
Thanks for the reply,

It seems I was using bad data on the address-end of the equation. The Address wasn't valid, so it was unable to return any sort of useful data.

The |raw tag was positioned incorrectly above, but was placed correctly in the twig tag in my code. It was just the bad data.

Thanks again!

**Comment by janhenckens** [comment]
Glad to here it worked out! Let me know if you run into anything else or if you'd like to see something added :)
