### ISSUE TITLE
Craft 3.5+ Return value of studioespresso\easyaddressfield\models\EasyAddressFieldModel::getCountryName() must be of the type string, none returned

### ISSUE THREAD

**Issue by chadcrowell** [studioespresso/craft3-easyaddressfield#25]
Never got this error before updating to Craft 3.5. Possible that the plugin needs an update for compatibility?

TypeError: Return value of studioespresso\easyaddressfield\models\EasyAddressFieldModel::getCountryName() must be of the type string, none returned in /var/www/gcx-craft.vhx.cloud/vendor/studioespresso/craft-easyaddressfield/src/models/EasyAddressFieldModel.php:191
Stack trace:
#0 /var/www/gcx-craft.vhx.cloud/vendor/twig/twig/src/Extension/CoreExtension.php(1499): studioespresso\easyaddressfield\models\EasyAddressFieldModel->getCountryName(Object(craft\i18n\Locale))
#1 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/helpers/Template.php(90): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(studioespresso\easyaddressfield\models\EasyAddressFieldModel), 'getCountryName', Array, 'method', false, false)
#2 /var/www/gcx-craft.vhx.cloud/storage/runtime/compiled_templates/b6/b6168e2e0677032ef371e367e67989c21ab2b5785d8513b65fb27e84873c073f.php(38): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(studioespresso\easyaddressfield\models\EasyAddressFieldModel), 'getCountryName', Array, 'method')
#3 /var/www/gcx-craft.vhx.cloud/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f0a772f09a78cb1e46038961784d24d4c29587721a2081b0221d7feaf6a70ba7->doDisplay(Array, Array)
#4 /var/www/gcx-craft.vhx.cloud/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/gcx-craft.vhx.cloud/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#6 /var/www/gcx-craft.vhx.cloud/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#7 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/web/View.php(543): Twig\TemplateWrapper->render(Array)
#8 /var/www/gcx-craft.vhx.cloud/vendor/besteadfast/craft-preparse-field/src/services/PreparseFieldService.php(105): craft\web\View->renderString('{{ element.addr...', Array)
#9 /var/www/gcx-craft.vhx.cloud/vendor/besteadfast/craft-preparse-field/src/services/PreparseFieldService.php(59): besteadfast\preparsefield\services\PreparseFieldService->parseField(Object(besteadfast\preparsefield\fields\PreparseFieldType), Object(craft\elements\Entry))
#10 /var/www/gcx-craft.vhx.cloud/vendor/besteadfast/craft-preparse-field/src/PreparseField.php(107): besteadfast\preparsefield\services\PreparseFieldService->getPreparseFieldsContent(Object(craft\elements\Entry), 'onSave')
#11 [internal function]: besteadfast\preparsefield\PreparseField->besteadfast\preparsefield\{closure}(Object(craft\events\ElementEvent))
#12 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#13 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#14 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/services/Elements.php(2470): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#15 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/services/Elements.php(2556): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false)
#16 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/services/Elements.php(2361): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), Array, Object(craft\elements\Entry))
#17 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/services/Elements.php(691): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#18 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/services/Drafts.php(201): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(167): craft\services\Drafts->saveElementAsDraft(Object(craft\elements\Entry), 1)
#20 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#21 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#23 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('create-draft', Array)
#24 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-draft', Array)
#25 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('entry-revisions...', Array)
#26 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entry-revisions...', Array)
#27 /var/www/gcx-craft.vhx.cloud/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /var/www/gcx-craft.vhx.cloud/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/www/gcx-craft.vhx.cloud/public_html/index.php(45): yii\base\Application->run()
#30 {main}

**Comment by janhenckens** [comment]
Hey @chadcrowell, could you post the address you're having the problem with?

**Comment by chadcrowell** [comment]
I'm not even getting that far. When I click New Entry or to edit any existing entry with an EA field, I am getting the error shown, both on local and production.

**Comment by janhenckens** [comment]
Ha yes, that's the problem. The field expects that there will always to something to return (aka every address has a country) but that doesn't hold up when you save it as empty off course.

Weird that the default country doesn't make it through but it's still an issue. Let me up wrap up a release that fixes it!

**Comment by janhenckens** [comment]
Fixed in 2.2.5, should be on composer in a couple of minutes.
