### ISSUE TITLE
Error 'Trying to access array offset on value of type float' when using field in job

### ISSUE THREAD

**Issue by bartroelands** [studioespresso/craft3-easyaddressfield#27]
Hi,

I am using the address field as part of an entry's fieldset that I am saving in the background in a plugin using a task. I am reading out an excel sheet with addresses that are then populated and saved. This works fine for most records in the file except for certain addresses where the job fails with an error 'Trying to access array offset on value of type float'. The log shows the error occurs in the file GeoLocationService.php:58.

This happens for specify addresses that are no different from the other addresses. 

2020-11-28 18:42:19 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-11-28 18:42:19 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [180] UploadTask (attempt: 1) - Error (time: 9.574s): Trying to access array offset on value of type float
2020-11-28 18:42:19 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to access array offset on value of type float in /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php:58
Stack trace:
#0 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php(58): craft\web\ErrorHandler->handleError()
#2 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php(32): studioespresso\easyaddressfield\services\GeoLocationService->geocodeOSM()
#3 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php(43): studioespresso\easyaddressfield\services\GeoLocationService->locate()
#4 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/studioespresso/craft-easyaddressfield/src/fields/EasyAddressFieldField.php(208): studioespresso\easyaddressfield\services\FieldService->saveField()
#5 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/base/Element.php(3199): studioespresso\easyaddressfield\fields\EasyAddressFieldField->afterElementSave()
#6 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/elements/Entry.php(1501): craft\base\Element->afterSave()
#7 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/services/Elements.php(2461): craft\elements\Entry->afterSave()
#8 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/services/Elements.php(764): craft\services\Elements->_saveElementInternal()
#9 /home/ubuntu/sites/learn2act-upload-1.0/src/services/UploadService.php(114): craft\services\Elements->saveElement()
#10 /home/ubuntu/sites/learn2act-upload-1.0/src/services/UploadService.php(58): learn2act\upload\services\UploadService->_createNewEntry()
#11 /home/ubuntu/sites/learn2act-upload-1.0/src/jobs/UploadTask.php(109): learn2act\upload\services\UploadService->processRecord()
#12 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2-queue/src/Queue.php(246): learn2act\upload\jobs\UploadTask->execute()
#13 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage()
#14 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/queue/Queue.php(121): yii\queue\cli\Queue->handleMessage()
#15 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#16 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/controllers/QueueController.php(105): craft\controllers\QueueController->actionRun()
#17 [internal function]: craft\controllers\QueueController->actionRetry()
#18 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#20 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#21 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#22 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#23 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#24 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#25 /home/ubuntu/sites/gedragstherapie-portal-sandbox/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#26 /home/ubuntu/sites/gedragstherapie-portal-sandbox/web/index.php(22): yii\base\Application->run()
#27 {main}

**Comment by ptindia** [comment]
As no data is provided in this log so not sure but I think you are getting some float data which you are trying to access an array so please do the type casting the fields you are getting this error. It should work.

**Comment by janhenckens** [comment]
hey @bartroelands, you'll have to check the data for the entries where it goes wrong. You can share the row that are causing the errors here if you'd like and I'll join you in having a look.

**Comment by bartroelands** [comment]
Hej @janhenckens I can share a particular address on which the api call seems to fail .. had a look myself @ the api (http://nominatim.openstreetmap.org/) but could not really see any problem with it ... address line is Kapucijnenvoer 16, 3000 Leuven .... seems to be known in the database ... https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=461159350&class=highway

**Comment by janhenckens** [comment]
Hey Bart, could you try again with the last update? Looks like I forgot to push the tag over the weekend, sorry about that. 3.0.1 should be available now!

**Comment by bartroelands** [comment]
Hej Jan, just ran a test on development and had no more errors ... looks
like it works now. Will deploy to staging and production now
