### ISSUE TITLE
'Calling unknown method' error

### ISSUE THREAD

**Issue by atimoda** [studioespresso/craft3-easyaddressfield#3]
I'm trying to get the static map, this way:
{{ espaco.endereco.getStaticMap }}

(where espaco.endereco is the field handle)

And it generates this error: 

"Calling unknown method: Studioespresso\easyaddressfield\models\EasyAddressFieldModel::getStaticMap()"

What am I doing wrong?
Sorry if posting this here is the wrong place, I could'nt find anywhere else to contact you.

**Comment by janhenckens** [comment]
Hey 

You can get a static map like this:
`{{ craft.easyaddressfield.getStaticMap(entry.addressFieldHandle) }}`

You can find more code snippets in the [readme](https://github.com/studioespresso/craft3-easyaddressfield).

**Comment by atimoda** [comment]
Still dont work... returns the error:
```
"Twig Runtime Error – Twig_Error_Runtime
Calling unknown method: craft\web\twig\variables\CraftVariable::easyaddressfield()"
```

If I try this, it works:
`{{ espaco.endereco.street }}`

but this dont work:
`{{ craft.easyaddressfield.getStaticMap(espaco.endereco) }}`

**Comment by janhenckens** [comment]
My bad, I got the variable name wrong (it's wrong in the readme too, fixing that asap).

You'll want to use:
`{{ craft.address.getStaticMap(espaco.endereco) }}` or `{{ craft.address.getStaticMap(espaco.endereco)|raw }}` to actually render the map.
