### ISSUE TITLE
Composer dependency issue

### ISSUE THREAD

**Issue by AndrewMac** [studioespresso/craft3-easyaddressfield#32]
Hello there! 

I'm trying to install version 4, under Craft 4 Beta, but I run into a composer dependency issue. Apparently, the issue is that other plugins I use are using a newer version of giggsey/locale (see below). Is it possible for Easy Address Field to move to ^2.0, or is that not possible at the moment?

```
studioespresso/craft-easyaddressfield[4.0.0-beta.1, ..., 4.0.0] require giggsey/locale ^1.0.0 -> found giggsey/locale[1.0, ..., 1.9] but the package is fixed to 2.2 (lock file version) by a partial update and that version does not match.
```

Thanks in advance for any help or advice you may be able to give with this.

Cheers, Andrew

**Comment by janhenckens** [comment]
Hey Andrew, good catch! It's probably safe to update giggsey/locale to 2 or higher, I'll have look tonight!

**Comment by janhenckens** [comment]
Just tagged 4.0.1, which should fix this. Can you give it a try @AndrewMac?

**Comment by AndrewMac** [comment]
Hi Jan
Thanks so much for your help with that.
I can confirm that I installed 4.0.1 without any problem! :-)

Cheers, Andrew

**Comment by janhenckens** [comment]
Cheers! Happy upgrading!
