### ISSUE TITLE
isEmpty function does not work correctly

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft3-easyaddressfield#33]
The isEmpty function in the `EasyAddressFieldModel.php` has an array of values which is never empty because it always contains following values:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/55497252/171345550-15f946c0-b2e1-41b4-add0-44c16983222f.png">

The isEmpty function:
![image](https://user-images.githubusercontent.com/55497252/171345627-a734dbbb-164c-4cc5-97c2-bbcdb0bb717c.png)

**Comment by janhenckens** [comment]
Fixed & released in 4.0.2. Can you update and try again?
