### ISSUE TITLE
Map icon overlaps with other elements and is inaccessible

### ISSUE THREAD

**Issue by MoritzLost** [studioespresso/craft3-easyaddressfield#36]
The easy address field displays a small map icon on the right side above the input fields, in the same line as the label. This icon overlaps with the field handle that is displayed when the user has the option _Show field handles in edit forms_ activated:

![Screenshot of the icon overlapping the field handle](https://user-images.githubusercontent.com/10146880/226322379-5f7b4fe1-59a7-4e50-b6d3-e09d98f2c60b.png)

Furthermore, if the field label is long enough to reach the end of the line, the icon overlaps that as well. It should probably be placed somewhere it can't overlap with either the field handle or the label.

Beyond that, clicking on the icon opens the map, allowing the user to pick an address on the map. This presents usability and accessibility issues:

- There is no accessible text alternative for the icon, so it's inaccessible to screen readers.
- There is no indication that clicking on the icon will yield this functionality.

To solve both the overlapping and the accessibility issues, I would suggest to move the icon below the label or below the set of input fields and add a text link to it:

![address-picker-text-link](https://user-images.githubusercontent.com/10146880/226324035-a8b5037b-e1a5-41e1-92dd-dafafe0316e7.png)

**Comment by janhenckens** [comment]
Hey @MoritzLost, that's great suggestion! And a quick fix too, I should have it out later this week.

**Comment by janhenckens** [comment]
Released this in 4.0.6, can you give that a try @MoritzLost? Thanks!

**Comment by MoritzLost** [comment]
@janhenckens Thanks for the quick response! Looks good and works 👍
I only noticed that the wrapper element is still a `<div>`, not an `<a>`. This means it can't be targeted by keyboard navigation and can't be clicked by hitting the space bar. Using an `<a>` element would solve both of those accessibility issues.

By the way, the changelog for the plugin was empty in the updates list:

![Screenshot 2023-03-20 at 17 20 51](https://user-images.githubusercontent.com/10146880/226406288-ccb1f156-b9f1-41f2-8a83-71d978f0c405.png)

Not sure why, maybe the changelog needs to be `CHANGELOG.md` instead of `CHANGELOG.MD`?

**Comment by janhenckens** [comment]
hey @MoritzLost, changed it to an href in 4.0.7.
Weird that the changelog isn't showing up, will look into it!
