### ISSUE TITLE
How to set custom settings?

### ISSUE THREAD

**Issue by atimoda** [studioespresso/craft3-easyaddressfield#4]
I see in the docs that there is some settings, but where can I find how to set them when outputting a map in a template?

Could'nt figure out by myself...

Thanks

**Comment by janhenckens** [comment]
Hey!

Yep, there's a bunch of settings but I see my readme could be a *bit* more extended on that part. 

Here's a an example:

If you want to show a basic static map, without any options, use this in your template:
`{{ craft.address.getStaticMap(entry.addressField)|raw }}`

The result will look like this:
![staticmap](https://user-images.githubusercontent.com/755428/36629232-849f972a-1953-11e8-8655-7b06df59f7d7.png)


Here's an example with custom settings include:
`{{ craft.address.getStaticMap(entry.addressField2, 16, '500x350', 'night', '#00ff00')|raw }}`

The result:
![staticmap-2](https://user-images.githubusercontent.com/755428/36629258-deaf1600-1953-11e8-8718-fc95bf305779.png)

Here are all the available settings:
- data (the field or fields to use)
- zoom (the zoom level, integer between 0 & 21)
- size (widthxheight, defaults to 640x640 which is also the maximum size)
- style (name of the style the map should be using, falls back to the style set in settings)
- color (hex value to be used as color for the marker(s), fallback to the color set in settings)
- icon (url that should be used as icon for the marker(s))
- scale (the scale level of the image, integer, 1 or 2)

Does this clear things up? I'll add some practical code samples to the readme too
Let me know if there's anything else you need help with!

Cheers
Jan

**Comment by janhenckens** [comment]
Added! https://github.com/studioespresso/craft3-easyaddressfield#examples
