### ISSUE TITLE
Receiving a g.co/staticmap error and nothing else when in dev mode.

### ISSUE THREAD

**Issue by moorebrett0** [studioespresso/craft3-easyaddressfield#8]
Hello when accessing my address field with any API keys, I am receiving the following:

g.co/staticmaperror and a blue map of the ocean.

 {{ craft.address.getStaticMap(block.address, 15, '500x350')|raw }} is my desired method.

**Comment by janhenckens** [comment]
Hey

Can you check https://developers.google.com/maps/documentation/maps-static/error-messages#warnings to see which of these errors you are getting? for `getStaticMap` to work, the static map API has to be enabled for the project your API key is in.

**Comment by moorebrett0** [comment]
Ah thank you!
