### ISSUE TITLE
CraftQL Support

### ISSUE THREAD

**Issue by tinchalamo** [studioespresso/craft3-easyaddressfield#9]
Is it possible to surface data from this field via [CraftQL](https://github.com/markhuot/craftql)?

**Comment by janhenckens** [comment]
I added this on Saturday but I don't have any experience with GraphQL and don't have a real app to test it with. 
If you want to, you can try it out by changing the version for the plugin in your composer.json to `dev-develop as 1.1.4`. Let me know how that goes and if all is good I'll release it to the store.

**Comment by tinchalamo** [comment]
@janhenckens how did you go about implementing this? I'm not seeing `craftQlGetFieldSchema` in your codebase. There's a section on [Third-party Field Support](https://github.com/markhuot/craftql#third-pary-field-support) that details how plugin developers can add CraftQL support.

I really appreciate you taking the time to implement this!

**Comment by janhenckens** [comment]
Dang, forgot to actually push the feature branch, silly me :)
You can find it here: https://github.com/studioespresso/craft3-easyaddressfield/blob/feature/craftql/src/EasyAddressField.php#L68

**Comment by janhenckens** [comment]
Hey @tinchalamo Did you get a chance to try this out?
